Force an upgrade to Gradle 6.8, which I think is appropriate for OpenJDK 15.
The commands I used were:

- gradle wrapper --gradle-version 6.8
- ./gradlew clean build
- ./gradlew build

I am indebted to https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2 and
https://stackoverflow.com/questions/61289461/java-lang-noclassdeffounderror-could-not-initialize-class-org-codehaus-groovy-v
for their insights.